### ISSUE TITLE
Captcha does not validate on production

### ISSUE THREAD

**Issue by andreyshipilov** [barbuza/supercaptcha#3]
Hi there.

My problem is that captcha works and validates while development locally. When deployed on production no matter what you submit, right symbols or not, captcha always has errors after submit. Basically the form can't be validated.

Any clue what could it be?

Thanks ahead.

**Comment by barbuza** [comment]
Hey, check your settings for valid and working cache backend

**Comment by andreyshipilov** [comment]
Yep. Will do now. Thanks.

**Comment by andreyshipilov** [comment]
Done. Fixed.
Спасибо. :)
